services:
  psql_bp:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${BLUEPRINT_DB_DATABASE}
      POSTGRES_USER: ${BLUEPRINT_DB_USERNAME}
      POSTGRES_PASSWORD: ${BLUEPRINT_DB_PASSWORD}
    ports:
      - "${BLUEPRINT_DB_PORT}:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "80MB"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --maxmemory 30mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "40MB"

  api-1:
    build: .
    restart: unless-stopped
    environment:
      - PORT=8080
      - BLUEPRINT_DB_HOST=psql_bp
      - BLUEPRINT_DB_PORT=5432
      - BLUEPRINT_DB_DATABASE=${BLUEPRINT_DB_DATABASE}
      - BLUEPRINT_DB_USERNAME=${BLUEPRINT_DB_USERNAME}
      - BLUEPRINT_DB_PASSWORD=${BLUEPRINT_DB_PASSWORD}
      - BLUEPRINT_DB_SCHEMA=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    ports:
      - "8081:8080"
    depends_on:
      - psql_bp
      - redis
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "90MB"

  api-2:
    build: .
    restart: unless-stopped
    environment:
      - PORT=8080
      - BLUEPRINT_DB_HOST=psql_bp
      - BLUEPRINT_DB_PORT=5432
      - BLUEPRINT_DB_DATABASE=${BLUEPRINT_DB_DATABASE}
      - BLUEPRINT_DB_USERNAME=${BLUEPRINT_DB_USERNAME}
      - BLUEPRINT_DB_PASSWORD=${BLUEPRINT_DB_PASSWORD}
      - BLUEPRINT_DB_SCHEMA=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    ports:
      - "8082:8080"
    depends_on:
      - psql_bp
      - redis
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "90MB"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "50MB"

volumes:
  psql_volume_bp:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
    name: payment-processor
